sets.exported={
    main="Sequence",
    sub={ name="Colada", augments={'Crit.hit rate+2','AGI+3','Accuracy+11','Attack+18','DMG:+15',}},
    ammo="Vanir Battery",
    head={ name="Herculean Helm", augments={'Accuracy+1','Weapon skill damage +4%','INT+4','Attack+10',}},
    body="Passion Jacket",
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs={ name="Lengo Pants", augments={'INT+7','Mag. Acc.+8','"Mag.Atk.Bns."+7',}},
    feet={ name="Medium's Sabots", augments={'MP+50','MND+8','"Conserve MP"+6','"Cure" potency +3%',}},
    neck="Twilight Torque",
    waist="Flume Belt",
    left_ear="Etiolation Earring",
    right_ear="Volunt. Earring",
    left_ring="Defending Ring",
    right_ring="Vengeful Ring",
    back="Solemnity Cape",
}