sets.exported={
    main="Bolelabunga",
    sub="Genmei Shield",
    range="Dunna",
    head="Azimuth Hood",
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+10 "Mag.Atk.Bns."+10','Magic burst dmg.+10%','MND+7','Mag. Acc.+10','"Mag.Atk.Bns."+5',}},
    hands="Geo. Mitaines +1",
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet="Geo. Sandals +1",
    neck="Twilight Torque",
    waist="Isa Belt",
    left_ear="Rimeice Earring",
    right_ear="Handler's Earring +1",
    left_ring="Vocane Ring",
    right_ring={ name="Dark Ring", augments={'Breath dmg. taken -3%','Magic dmg. taken -4%','Phys. dmg. taken -4%',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+25%','MND+1','DEF+3',}},
}