sets.exported={
    main="Sequence",
    sub="Aegis",
    ammo="Homiliary",
    head={ name="Valorous Mask", augments={'Attack+29','Weapon skill damage +4%','Accuracy+11',}},
    body="Councilor's Garb",
    hands={ name="Souv. Handschuhs", augments={'HP+50','Shield skill +10','Phys. dmg. taken -3',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Sulev. Leggings +1",
    neck="Coatl Gorget +1",
    waist="Chuq'aba Belt",
    left_ear="Genmei Earring",
    right_ear="Infused Earring",
    left_ring="Paguroidea Ring",
    right_ring="Sheltered Ring",
    back={ name="Rudianos's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','Haste+10','Damage taken-5%',}},
}