sets.exported={
    main="Sequence",
    sub={ name="Colada", augments={'Crit.hit rate+2','AGI+3','Accuracy+11','Attack+18','DMG:+15',}},
    ammo="Vanir Battery",
    head="Rawhide Mask",
    body="Jhakri Robe +1",
    hands="Aya. Manopolas +1",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Battlecast Gaiters",
    neck="Bathy Choker +1",
    waist="Fucho-no-Obi",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Sheltered Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Damage taken-5%',}},
}