sets.exported={
    main="Bolelabunga",
    sub="Genmei Shield",
    range="Dunna",
    head="Azimuth Hood",
    body="Jhakri Robe +1",
    hands="Geo. Mitaines +1",
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet={ name="Bagua Sandals +1", augments={'Enhances "Radial Arcana" effect',}},
    neck="Twilight Torque",
    waist="Isa Belt",
    left_ear="Rimeice Earring",
    right_ear="Handler's Earring +1",
    left_ring="Vocane Ring",
    right_ring={ name="Dark Ring", augments={'Breath dmg. taken -3%','Magic dmg. taken -4%','Phys. dmg. taken -4%',}},
    back={ name="Nantosuelta's Cape", augments={'Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10','Pet: Damage taken -4%',}},
}