sets.exported={
    main="Sequence",
    sub={ name="Colada", augments={'Crit.hit rate+2','AGI+3','Accuracy+11','Attack+18','DMG:+15',}},
    ammo="Vanir Battery",
    head="Rawhide Mask",
    body="Councilor's Garb",
    hands="Serpentes Cuffs",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Serpentes Sabots",
    neck="Bathy Choker +1",
    waist="Fucho-no-Obi",
    left_ear="Genmei Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Sheltered Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10','Damage taken-5%',}},
}