sets.exported={
    main="Fettering Blade",
    sub="Demers. Degen +1",
    range={ name="Doomsday", augments={'Mag. Acc.+8','Phys. dmg. taken -2%','STR+15 AGI+15',}},
    head="Meghanada Visor +1",
    body="Councilor's Garb",
    hands="Umuthi Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Herculean Boots", augments={'Accuracy+15 Attack+15','"Triple Atk."+3','AGI+10','Accuracy+9',}},
    neck="Twilight Torque",
    waist="Kentarch Belt +1",
    left_ear="Genmei Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Vocane Ring",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+8','"Dbl.Atk."+10','Damage taken-5%',}},
}