sets.exported={
    main={ name="Rubicundity", augments={'Mag. Acc.+4','"Mag.Atk.Bns."+5','Dark magic skill +2','"Conserve MP"+3',}},
    sub="Genmei Shield",
    range="Dunna",
    ammo="Sapience Orb",
    head={ name="Bagua Galero +1", augments={'Enhances "Primeval Zeal" effect',}},
    body={ name="Bagua Tunic +1", augments={'Enhances "Bolster" effect',}},
    hands={ name="Bagua Mitaines +1", augments={'Enhances "Curative Recantation" effect',}},
    legs={ name="Bagua Pants +1", augments={'Enhances "Mending Halation" effect',}},
    feet={ name="Bagua Sandals +1", augments={'Enhances "Radial Arcana" effect',}},
    neck="Incanter's Torque",
    waist="Austerity Belt",
    left_ear="Mendi. Earring",
    right_ear="Friomisi Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +9','Indi. eff. dur. +17',}},
}