sets.exported={
    main={ name="Rubicundity", augments={'Mag. Acc.+4','"Mag.Atk.Bns."+5','Dark magic skill +2','"Conserve MP"+3',}},
    sub="Genmei Shield",
    range="Dunna",
    head="Azimuth Hood",
    body={ name="Bagua Tunic +1", augments={'Enhances "Bolster" effect',}},
    hands="Geo. Mitaines +1",
    legs={ name="Bagua Pants +1", augments={'Enhances "Mending Halation" effect',}},
    feet={ name="Medium's Sabots", augments={'MP+50','MND+8','"Conserve MP"+6','"Cure" potency +3%',}},
    neck="Incanter's Torque",
    waist="Austerity Belt",
    left_ear="Mendi. Earring",
    right_ear="Friomisi Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
}