sets.exported={
    main="Fettering Blade",
    sub="Demers. Degen +1",
    range={ name="Doomsday", augments={'Mag. Acc.+8','Phys. dmg. taken -2%','STR+15 AGI+15',}},
    ammo="Eminent Bullet",
    head="Meghanada Visor +1",
    body="Mummu Jacket +1",
    hands={ name="Adhemar Wristbands", augments={'DEX+10','AGI+10','Accuracy+15',}},
    legs="Meg. Chausses +1",
    feet="Meg. Jam. +1",
    neck="Sanctity Necklace",
    waist="Impulse Belt",
    left_ear="Neritic Earring",
    right_ear="Telos Earring",
    left_ring="Petrov Ring",
    right_ring="Rajas Ring",
    back="Camulus's Mantle",
}